diff -ru -x '*~' src-orig/Makefile src-patched/Makefile
--- src-orig/Makefile	1970-01-01 01:00:01.000000000 +0100
+++ src-patched/Makefile	2020-04-28 12:36:28.058406028 +0200
@@ -50,22 +50,12 @@
 	# versions of the SQLite source code results in a change to the
 	# modification time for the src-SQLite directory, which in turn results
 	# in a rebuild of another version.
-	if [ ! -d src-SQLite ] ; then \
-		git clone --shallow-since 2013-05-19 \
-			https://github.com/sqlite/sqlite.git src-SQLite && \
-		git -C src-SQLite fetch origin \
-			'refs/tags/version-3.3*:refs/tags/version-3.3*' ; \
-	fi
-	git -C src-SQLite checkout version-$*
 	rm -rf $@ && mkdir $@
 	cd $@ && ../src-SQLite/configure && cd ..
 	make -C $@
 	$@/sqlite3 --version
 
 bld-LMDB_%:
-	test -d src-lmdb || \
-	git clone https://github.com/LMDB/lmdb.git src-lmdb
-	git -C src-lmdb checkout LMDB_$*
 	rm -rf $@ && mkdir $@
 	cp LICENSES/Apache-2.0.txt $@/LICENSE
 	cd $@ && ../lmdb-backend/configure \
@@ -82,8 +72,7 @@
 	make -C $@
 	$@/sqlite3 --version
 
-%.html: bld-%
-	ln -s $</sqlite3
+%.html:
 	tclsh tool/speedtest.tcl | tee $@
 	rm -f sqlite3 test*.sql clear.sql 2kinit.sql s2k.db s2k.db-lock
 
